# Generated by Django 5.2.16 on 2026-07-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_activeclient_converted_at_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название контракта')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='Файл контракта')),
                ('date_signed', models.DateField(verbose_name='Дата заключения')),
                ('validity_period', models.PositiveIntegerField(verbose_name='Срок действия (в днях)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('active_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.activeclient', verbose_name='Активный клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='services.service', verbose_name='Услуга')),
            ],
        ),
    ]
