# Generated by Django 5.2.16 on 2026-07-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название контракта')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='Файл контракта')),
                ('start_date', models.DateField(verbose_name='Дата заключения')),
                ('end_date', models.DateField(verbose_name='Дата истечения')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer', verbose_name='Активный клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.product', verbose_name='Услуга')),
            ],
        ),
    ]
