# Generated by Django 5.2.16 on 2026-07-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('channel', models.CharField(max_length=100, verbose_name='Канал продвижения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='services.service', verbose_name='Рекламируемая услуга')),
            ],
        ),
    ]
