# Generated by Django 5.2.16 on 2026-07-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('can_view_statistics', 'Может просматривать статистику рекламных кампаний')]},
        ),
    ]
