# Generated by Django 5.2.16 on 2026-07-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_client', to='prospects.prospect', verbose_name='Потенциальный клиент')),
            ],
        ),
    ]
