# Generated by Django 5.2.16 on 2026-07-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclient',
            name='converted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата перевода'),
        ),
        migrations.AlterField(
            model_name='activeclient',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_client', to='prospects.prospect', verbose_name='Клиент'),
        ),
    ]
